// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// 静的ファイルの型定義
declare module "*.ico" {
  const src: string;
  export default src;
}

import {
  KintoneAuth,
  KintoneApp,
  KintoneField,
  KintoneUser,
  KintoneRecord,
} from "./types/kintone";

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
  toggleDevTools: () => Promise<void>;
  openDevTools: () => Promise<void>;
  closeDevTools: () => Promise<void>;
}

interface KintoneAPIContext {
  login: (auth: KintoneAuth) => Promise<{ success: boolean; error?: string }>;
  getApps: (
    auth: KintoneAuth,
  ) => Promise<{ success: boolean; data?: KintoneApp[]; error?: string }>;
  getAppFields: (
    auth: KintoneAuth,
    appId: string,
  ) => Promise<{ success: boolean; data?: KintoneField[]; error?: string }>;
  executeQuery: (
    auth: KintoneAuth,
    appId: string,
    query: string,
  ) => Promise<{
    success: boolean;
    data?: { records: KintoneRecord[]; totalCount: number };
    error?: string;
  }>;
  getUsers: (
    auth: KintoneAuth,
  ) => Promise<{ success: boolean; data?: KintoneUser[]; error?: string }>;
}

interface AppInfo {
  version: string;
  license: string;
  author: string;
  productName: string;
  description: string;
  homepage: string;
  licenseExpiry: string;
}

interface ElectronAppAPIContext {
  getAppInfo: () => Promise<AppInfo>;
  updateLicenseExpiry: (newExpiry: string) => Promise<{ success: boolean; error?: string }>;
  quit: () => Promise<void>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  kintoneAPI: KintoneAPIContext;
  electronAppAPI: ElectronAppAPIContext;
}
